## Numpy array and basics
learn about numpy with chai!

In [1]:
import numpy as np
import time

## Creating array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array: ", arr_1d)

1D Array:  [1 2 3 4 5]


In [3]:
arr_2d = np.array ([[1,2,3],[4,5,6]])
print("2D Array: ", arr_2d)

2D Array:  [[1 2 3]
 [4 5 6]]


## List vs Numpy array

In [4]:
py_list = [1,2,3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1,2,3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.array(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.07911205291748047

 Numpy operation time:  0.0001480579376220703


### Creating array from scratch

In [5]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((3,4))
print("Ones array: \n", ones)


full = np.full((2,4), 7)
print("Full array: \n", full)


random = np.random.random((2,4))
print("Random array: \n", random)


sequence = np.arange(0,10,2)
print("Sequence array: \n", sequence)



Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array: 
 [[7 7 7 7]
 [7 7 7 7]]
Random array: 
 [[0.19023121 0.18088119 0.76171855 0.61227539]
 [0.31097099 0.08933251 0.90251729 0.07513412]]
Sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [6]:
vector = np.array([1,2,3])
print("Vector: ",vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("Matrix: ",matrix)

tensor = np.array([[[1,2,3], [4,5,6]],[[3,2,3], [3,5,6]]])
print("Tensor: ",tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2 3]
  [4 5 6]]

 [[3 2 3]
  [3 5 6]]]


### Array Properties

In [7]:
arr =  np.array([[1,2,3],[4,5,6]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data type: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Data type:  int64


### Array Reshaping

In [8]:
arr = np.arange(12)
print("Original Array: ",arr)

reshaped = arr.reshape((3,4)) #should be perfect size of element in array
print("\n Reshaped array: ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: ", flattened)

#ravel (return view, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled array: ", raveled)

#Transpose
transposed = reshaped.T
print("\n transposed array: ", transposed)


Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
