### Numpy Array Operations

In [1]:
import numpy as np

In [2]:
# 1D Arr Slicing
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing", arr[2:7])

print("with steps ",arr[2:8:3])
print("Negative indexing ",arr[-3])

Basic Slicing [3 4 5 6 7]
with steps  [3 6]
Negative indexing  8


In [3]:
# 2D Arr Slicing
arr_2d = np.array([[1,2,3,4],[3,5,7,9],[1,4,9,10]])
print("Specific Element ", arr_2d[1,2])
print("Entire row ", arr_2d[1])
print("Entire row ", arr_2d[:,2])

Specific Element  7
Entire row  [3 5 7 9]
Entire row  [3 7 9]


### Sorting

In [4]:
unsorted = np.array([3,2,4,2,4,8,1,9,5,6])

print("Sorted Arr ",np.sort(unsorted))
arr_2_unsorted = np.array([[3,8,5],[4,5,1],[1,5,3]])
print("Sorted 2D Arr by column ",np.sort(arr_2_unsorted,axis=0))
print("Sorted 2D Arr by row ",np.sort(arr_2_unsorted,axis=1))



Sorted Arr  [1 2 2 3 4 4 5 6 8 9]
Sorted 2D Arr by column  [[1 5 1]
 [3 5 3]
 [4 8 5]]
Sorted 2D Arr by row  [[3 5 8]
 [1 4 5]
 [1 3 5]]


## Filter

In [5]:
numbers = np.arange(11)
even_number = numbers[numbers % 2 == 0]
print("Even Numbers", even_number)

Even Numbers [ 0  2  4  6  8 10]


### Filter with mask

In [6]:
mask = numbers > 5
print("Number greater than 5 ", numbers[mask])

Number greater than 5  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [7]:
indices = [0,2,4,6]
print(numbers[indices])

[0 2 4 6]


In [8]:
where_result = np.where(numbers > 5)
print(where_result)
print("NP Where ",numbers[where_result])

(array([ 6,  7,  8,  9, 10]),)
NP Where  [ 6  7  8  9 10]


In [11]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print("condition arr ",condition_array)

condition_array2 = np.where(numbers > 5, True, False)
print("condition arr ",condition_array2)

condition arr  [ 0  1  2  3  4  5 12 14 16 18 20]
condition arr  [False False False False False False  True  True  True  True  True]


## Adding and removing data

In [12]:
arr1 = np.array([1,4,8])
arr2 = np.array([3,2,6])

combined = np.concatenate((arr1,arr2))
print("Combined: ",combined)

Combined:  [1 4 8 3 2 6]


### Array compatibility

In [17]:
a = np.array([1,4,5])
b = np.array([5,3,6,9])
c = np.array([2,4,8])

print("Compatibility Shapes", a.shape == b.shape)
print("Compatibility Shapes", a.shape == c.shape)


Compatibility Shapes False
Compatibility Shapes True


In [23]:
original = np.array([[2,5],[1,4]])
new_row = np.array([[6,9]])

with_new_row = np.vstack([original, new_row])
print(with_new_row)

new_column = np.array([[4], [9]])
with_new_column = np.hstack((original, new_column))
print(with_new_column)

[[2 5]
 [1 4]
 [6 9]]
[[2 5 4]
 [1 4 9]]


In [24]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Arr after deletion: ", deleted)

Arr after deletion:  [1 2 4 5]
